# Site settings
title: Presentazioni
author: ulaulaman
avatar: https://avatars.githubusercontent.com/u/34242086?v=4
description: "Una prova di costruzione del sito"

# Build settings
remote_theme: zivong/jekyll-theme-hamilton
skin: midnight
