# Site settings
title: GPresentazioni
author: 
  name: ulaulaman
description: "Un piccolo blog per le mie presentazioni"

# Build settings
remote_theme: jekyll/minima

minima:
  skin: solarized-dark
  show_excerpts: true
  social_links:
    - title: ulaulaman's repository at GitHub
      icon: github
      url: "https://github.com/ulaulaman"